# Generated by Django 4.2.1 on 2023-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('S', 'Sayur'), ('B', 'Buah'), ('DS', 'Daging dan Seafood'), ('TO', 'Telur dan Olahan Susu')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SALE', 'SALE'), ('BEST', 'BEST')], max_length=4),
        ),
    ]
